project_id = "ovkkvqavropsrxupjtsm"

[functions.optimize-receipt]
verify_jwt = false

[functions.initialize-certificate-payment]
verify_jwt = false

[functions.send-enrollment-email]
verify_jwt = false
