
-- Insert 7 new cohort-based courses
INSERT INTO public.courses (title, slug, course_type, status, description, short_description, category, level)
VALUES
  ('Clinical Research & Health Data Analytics', 'clinical-research-health-data-analytics', 'cohort', 'published', 'Master the fundamentals of clinical research methodology, health data collection, analysis, and interpretation. Learn to design clinical trials, manage research data, and apply statistical methods to healthcare outcomes.', 'Master clinical research methodology and health data analytics.', 'Clinical Research & Data', 'intermediate'),
  ('Medical Coding & Health Information Management', 'medical-coding-health-information-management', 'cohort', 'published', 'Learn medical coding systems (ICD, CPT, HCPCS), health information management principles, electronic health records, and healthcare data governance. Prepare for a career in health information management.', 'Learn medical coding systems and health information management.', 'Diagnostics & Allied Health Skills', 'beginner'),
  ('HealthTech Product Management', 'healthtech-product-management', 'cohort', 'published', 'Develop skills in managing digital health products from ideation to launch. Cover product strategy, user research, agile development, regulatory considerations, and go-to-market strategies for health technology solutions.', 'Manage digital health products from ideation to launch.', 'Digital Health & Innovation', 'intermediate'),
  ('Digital Health & AI in Healthcare', 'digital-health-ai-in-healthcare', 'cohort', 'published', 'Explore the intersection of artificial intelligence and healthcare. Learn about AI applications in diagnostics, predictive analytics, natural language processing in clinical settings, and ethical considerations of AI in medicine.', 'Explore AI applications in diagnostics and healthcare delivery.', 'Digital Health & Innovation', 'intermediate'),
  ('Healthcare Design & Innovation', 'healthcare-design-innovation', 'cohort', 'published', 'Apply design thinking and innovation frameworks to solve complex healthcare challenges. Learn human-centered design, service design, rapid prototyping, and innovation management in healthcare settings.', 'Apply design thinking to solve healthcare challenges.', 'Digital Health & Innovation', 'beginner'),
  ('Advanced Public Health Leadership', 'advanced-public-health-leadership', 'cohort', 'published', 'Develop advanced leadership competencies for public health practice. Cover health policy analysis, program management, community health strategy, epidemiological leadership, and global health governance.', 'Develop advanced leadership skills for public health practice.', 'Public Health & Health Systems', 'advanced'),
  ('ECG & Basic Cardiology Interpretation', 'ecg-basic-cardiology-interpretation', 'cohort', 'published', 'Learn systematic ECG interpretation, basic cardiac electrophysiology, recognition of common arrhythmias, and clinical correlation of ECG findings. Ideal for healthcare professionals seeking cardiology competencies.', 'Learn systematic ECG interpretation and basic cardiology.', 'Emergency & Clinical Skills', 'intermediate');
