// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovkkvqavropsrxupjtsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92a2t2cWF2cm9wc3J4dXBqdHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4NTU5NjYsImV4cCI6MjA4NDQzMTk2Nn0.gLxO5TaqjQBsutL9tamqbiAJfdltXiiSBKANFo7Fazo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});